server:
  http_listen_port: 3200
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: node-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: node-metrics-app
          app: metrics-generator
          environment: dev
          __path__: /var/log/app/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            endpoint: endpoint
            status: status
            temperature: temperature
            connections: connections
            duration_ms: durationMs
            error_type: errorType
      - labels:
          level:
          endpoint:
          status:
          error_type:
      - output:
          source: message
